### ISSUE TITLE
Touch screen input

### ISSUE THREAD

**Issue by Guillem96** [Guillem96/argon-nx#1]
Handle payload selection using touch screen

**Comment by jakibaki** [comment]
Just in case you weren't aware: https://github.com/balika011/hekate/commit/021231199ee0873cedd49a95b0fb624449f93fcf

**Comment by Guillem96** [comment]
@jakibaki do you know another source where I can find info about touch input support?
Balika011 implementation doesn t work...

**Comment by jakibaki** [comment]
Nope, sorry :/

You might want to pm them on discord (They're at the very least in reswitched) and if they can't help maybe  take a look at the tegra x1-specs which are linked somewhere in switchbrew.

**Comment by Guillem96** [comment]
Yesterday I talked with him. He told me that he wont be able to help me
