### ISSUE TITLE
Use Vol + instead vol - to cancel autolaunch

### ISSUE THREAD

**Issue by Guillem96** [Guillem96/argon-nx#29]

**Comment by mrdude2478** [comment]
In main.c - change code to this:

    /* Mount Sd card and launch payload */
    if (sd_mount())
    {
        bool cancel_auto_chainloading = btn_read() & BTN_VOL_UP;
        bool load_menu = cancel_auto_chainloading || launch_payload("autoboot.bin");

This will allow the following: Power+short volume + press  (run designated payload.bin), Power + long press on volume + (run Argon menu).
