### ISSUE TITLE
Warmboot breaks linux video acceleration

### ISSUE THREAD

**Issue by GavinDarkglider** [Guillem96/argon-nx#34]
if you warmboot from atmosphere into argon-nx and then load coreboot it breaks video card acceleration. This is a simple patch, especially since you are using the hekate init code, and ctcaer has already fixed it in hekate. The fix can be found here: https://github.com/CTCaer/hekate/commit/4f2bbbf101f3fda0771685e0a40d6876005c2c36

I would prefer to use this as a warmboot payload, but would like to have it boot everything I use on my switch.

**Comment by GavinDarkglider** [comment]
Also, coreboot only works if you rename coreboot.rom to coreboot.bin. Argon-nx should support finding files with both the bin and rom extensions for payloads.

**Comment by Guillem96** [comment]
Thanks for the issue!
