### ISSUE TITLE
Reboot to OFW not working

### ISSUE THREAD

**Issue by mrdude2478** [Guillem96/argon-nx#39]
Rebooting to OFW is showing a black screen, and crashing the console. Changin panic code to this:

void panic_alt(u32 val)
{
    // Set panic code.
    PMC(APBDEV_PMC_SCRATCH200) = val;
    //PMC(APBDEV_PMC_CRYPTO_OP) = 1; // Disable SE.
    TMR(TIMER_WDT4_UNLOCK_PATTERN) = TIMER_MAGIC_PTRN;
    TMR(TIMER_TMR9_TMR_PTV) = TIMER_EN | TIMER_PER_EN;
    TMR(TIMER_WDT4_CONFIG)  = TIMER_SRC(9) | TIMER_PER(1) | TIMER_PMCRESET_EN;
    TMR(TIMER_WDT4_COMMAND) = TIMER_START_CNT;
    while (1)
        ;
}

I think in your code, when you execute code 'check_and_display_panic();' this is not working properly, as this is what's causing the issue for me. The code I posted above works though.

**Comment by Guillem96** [comment]
Thanks for opening this issue, feel free and make a pull request tu fix it
