### ISSUE TITLE
Custom icon layout

### ISSUE THREAD

**Issue by NO-ob** [Guillem96/argon-nx#40]
Not sure if it will be hard for you to implement or not, if it is dont worry about it but I was wondering if it would be possible to have a text file in the argon directory where you can specify the x and y co-ordinates of each logo and maybe the size to draw them at aswell

**Comment by Guillem96** [comment]
@NO-ob that's a good idea. Now I am quite busy but I hope I can start implementing it in a few days. :smiley:

**Comment by Guillem96** [comment]
With the new release, this change does not make sense
