### ISSUE TITLE
Fix battery desync issues caused by unpatched linux kernels on boot

### ISSUE THREAD

**Issue by GavinDarkglider** [Guillem96/argon-nx#46]
There was an option in hekate for this, but ctcaer decided when l4t-ubuntu was released, that this becomes more of a priority, so it is now applied on every boot to hekate, and removed from the menu. I dont want to have to boot to hekate to boot to atmosphere, and not have the console die when it is at 40% lol.

attached is a patch file to fix the issue.
[argon-nx-linux-fix-battery-desync-on-boot.txt](https://github.com/Guillem96/argon-nx/files/3237530/argon-nx-linux-fix-battery-desync-on-boot.txt)

**Comment by Guillem96** [comment]
Fixed :)
