### ISSUE TITLE
SX Gear Boot.dat

### ISSUE THREAD

**Issue by Nidhoeggur** [Guillem96/argon-nx#48]
Im using sxgear.
the problem is the boot.dat is opening the payload named payload.bin which is 4 me argon nx.
if i try now to start sxos the boot.dat will start argon.nx. 

it would be awesome if the sxos.bin would start sxos.dat.  So could i use the sxgear to launch argon and with argon sxos

**Comment by Guillem96** [comment]
I don't have SXOS I cannot test it, sorry man
