### ISSUE TITLE
v1.0-alpha no booting via Payloadsender possible

### ISSUE THREAD

**Issue by muxi1** [Guillem96/argon-nx#52]
v1.0-alpha  does not boot via tegrarcmGUI or a dongle. However, it works via Reboot to Payload. (If this file is renamed to reboot_payload.bin in the atmosphere folder)

**Comment by chronoss09** [comment]
blackscreen for me, not booting :(

**Comment by ogogo1** [comment]
same blackscreen no booting and if i use the old payload u see some stuff but no wallpaper or images but clicking them if u know the position of the icon works to boot into the correct system atmo , reinx etc

**Comment by Guillem96** [comment]
I ll take a look this week. In linux with fusee launcher I can conform that it works. I am gonna do some mlre testing and make a hot fix in case it fails.
Thanks for reporting the error :smiley:

**Comment by Guillem96** [comment]
Working with the new release (At least for me). If someone tests it and report that it is working I am gonna close the issue. @ogogo1 @chronoss09 @muxi1

**Comment by ogogo1** [comment]
> Working with the new release (At least for me). If someone tests it and report that it is working I am gonna close the issue. @ogogo1 @chronoss09 @muxi1

ty working now issue can be closed

**Comment by muxi1** [comment]
Yeah! It´s working now! Thanks!
