### ISSUE TITLE
v1.0-alpha No sending of payloads possible after screenshots have been created

### ISSUE THREAD

**Issue by muxi1** [Guillem96/argon-nx#53]
After screenshots of the different screens have been created, no payload can be started anymore. A message appears that a certain file can not be found.
Only by a reboot, the selection is possible again.

**Comment by Guillem96** [comment]
Thanks, I ll take a look

**Comment by Guillem96** [comment]
It works with the new 1.1 alpha release

**Comment by muxi1** [comment]
Thanks! Great work!
