### ISSUE TITLE
hekate

### ISSUE THREAD

**Issue by charlesmagnum** [Guillem96/argon-nx#59]
Hi.
i'm using R4 trincket,  last atmosphere and hekate - CTCaer mod v5.1.1 & Nyx v0.8.4
no matter if i click over atmosphere icon or hekate, it launches atmosphere only.
i have all the files set for bootloader and the new hekate_ctcaer_5.1.1.bin file on  /argon/payloads
properly renamed to hekate.bin.

**Comment by Guillem96** [comment]
Check your hekate settings. Make sure that you don't have autoboot on

**Comment by charlesmagnum** [comment]
> Check your hekate settings. Make sure that you don't have autoboot on

Thx bro, that was the issue.
Hekate was set to autoboot and load Atmosphere.bin.(this came by defualt on new downloaded file from hekate github).

Grateful for the answer since it wasn't Argon's trouble.
Best regards and thank you for this great tool.
