### ISSUE TITLE
R4S

### ISSUE THREAD

**Issue by kr-los** [Guillem96/argon-nx#61]
Se podría adaptar la versión "ArgonNX v1.1" para que funcione en el [Dongle R4S](http://www.r4i-sdhc.com/R4SDongles.asp)?

The version "ArgonNX v1.1" could be adapted to work in the [Dongle R4S](http://www.r4i-sdhc.com/R4SDongles.asp)?

**Comment by kr-los** [comment]
Me respondo, con este [archivo](https://raw.githubusercontent.com/mattytrog/Fusee-UF2/master/Fusee_UF2_V3/RCMX86_INTERNAL_FUSEE_UF2_V3.UF2), se puede hacer.

**Comment by charlesmagnum** [comment]
it works already, i have R4 tricket

**Comment by kr-los** [comment]
> it works already, i have R4 tricket

Que es el R4 tricket?

**Comment by charlesmagnum** [comment]
http://r4i-sdhc.com/#Download
You just need to load the UF2 file from this link into the dongle.
